<iframe
  width="600"
  height="450"
  style="border:0"
  loading="lazy"
  allowfullscreen
  referrerpolicy="no-referrer-when-downgrade"
  src="https://www.google.com/maps/embed/v1/place?key=AIzaSyA6u7UZdiNz3rkAZCsO-nSzr2Qgg7I0sLc
    &q=Space+Needle,Seattle+WA">
</iframe> 